// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about" data-webild-component="AboutMediaOverlay" data-webild-component-path="@/components/sections/about/AboutMediaOverlay">
            <SectionErrorBoundary name="about">
              <AboutMediaOverlay
                tag="Our Story"
                title="Unmatched Comfort in Tbilisi"
                description="Located at Agmashenebeli Alley, Tbilisi Tower combines luxury with accessibility. Whether you are here for sightseeing or business, our hotel provides the perfect home base with refined interiors and attentive service."
                imageSrc="http://img.b2bpic.net/free-photo/elegant-wedding-ceremony-venue-with-floral-decorations_23-2151976686.jpg"
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
