// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "amenities" section.

import React from 'react';
import FeaturesBento from '@/components/sections/features/FeaturesBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function homeSection(): React.JSX.Element {
  return (
    <div id="amenities" data-section="amenities" data-webild-component="FeaturesBento" data-webild-component-path="@/components/sections/features/FeaturesBento">
            <SectionErrorBoundary name="amenities">
              <FeaturesBento
                tag="Key home"
                title="Everything for Your Stay"
                description="Relax and recharge with our high-end facilities tailored for your convenience."
                features={[
                  {
                    title: "Wellness & Leisure",                description: "Dive into our refreshing indoor pool.",                bentoComponent: "media-stack",                mediaItems: [
                      { imageSrc: "http://img.b2bpic.net/free-photo/luxury-resort-pool-paradise_23-2151961791.jpg" },
                      { imageSrc: "http://img.b2bpic.net/free-photo/gym-interior-with-equipment_93675-129242.jpg" },
                      { imageSrc: "http://img.b2bpic.net/free-photo/spa-decoration-wood-background_1150-6743.jpg" }
                    ]
                  },
                  {
                    title: "Stay Connected",                description: "High-speed Wi-Fi available throughout the premises.",                bentoComponent: "orbiting-icons",                centerIcon: "Wifi",                orbitIcons: ["Smartphone", "Laptop", "Globe"]
                  },
                  {
                    title: "Dining Excellence",                description: "Enjoy fresh, local, and international cuisine.",                bentoComponent: "info-card-marquee",                infoCards: [
                      { icon: "Utensils", label: "Breakfast", value: "Available" },
                      { icon: "Coffee", label: "Restaurant", value: "On-Site" }
                    ]
                  }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
