// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact" data-webild-component="ContactCta" data-webild-component-path="@/components/sections/contact/ContactCta">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="Reservations"
                text="Ready to book your stay in Tbilisi? Call us today to secure your reservation at the best rates."
                primaryButton={{ text: "Call 599 81 88 88", href: "tel:599818888" }}
                secondaryButton={{ text: "Email Us", href: "mailto:info@tbilisitower.ge" }}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
