// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq" data-webild-component="FaqTwoColumn" data-webild-component-path="@/components/sections/faq/FaqTwoColumn">
            <SectionErrorBoundary name="faq">
              <FaqTwoColumn
        tag="Support"
        title="Frequently Asked Questions"
        description="Answers to commonly asked questions about your visit."
        items={[{"answer":"Check-in is at 14:00 (2:00 PM) and check-out is at 12:00 (12:00 PM).","question":"What are the check-in and check-out times?"},{"answer":"We offer paid breakfast options for our guests, though some booking platforms like Skyscanner and Agoda may include free breakfast in their rates.","question":"Is breakfast included?"},{"answer":"Yes, we offer free parking for all guests during their stay.","question":"Do you have free parking?"},{"answer":"Rates typically start around 234-235 GEL per night for 2 adults, depending on the booking platform and season.","question":"What are your room rates?"}]}
        textAnimation="slide-up"
      />
            </SectionErrorBoundary>
          </div>
  );
}
