// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "footer" section.

import React from 'react';
import FooterBasic from '@/components/sections/footer/FooterBasic';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FooterSection(): React.JSX.Element {
  return (
    <div id="footer" data-section="footer" data-webild-component="FooterBasic" data-webild-component-path="@/components/sections/footer/FooterBasic">
            <SectionErrorBoundary name="footer">
              <FooterBasic
                columns={[
                  { title: "Location", items: [{ label: "Agmashenebeli Alley 7th km" }, { label: "Tbilisi, 0131" }] },
                  { title: "Support", items: [{ label: "FAQ" }, { label: "Privacy Policy" }] }
                ]}
                leftText="© 2025 Hotel Tbilisi Tower. All rights reserved."
                rightText="Designed with hospitality in mind."
              />
            </SectionErrorBoundary>
          </div>
  );
}
