// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics" data-webild-component="MetricsSimpleCards" data-webild-component-path="@/components/sections/metrics/MetricsSimpleCards">
            <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
                tag="Statistics"
                title="Why Guests Choose Us"
                description="Consistently rated for our comfort and central location."
                metrics={[
                  { value: "3.9", description: "Average Star Rating" },
                  { value: "837", description: "Happy Guest Reviews" },
                  { value: "3.5/5", description: "Location Score" }
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
