// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials" data-webild-component="TestimonialColumnMarqueeCards" data-webild-component-path="@/components/sections/testimonial/TestimonialColumnMarqueeCards">
            <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
                tag="Guest Voices"
                title="Stories from Our Guests"
                description="Hear what travelers say about their stay at Tbilisi Tower."
                testimonials={[
                  { name: "Anna V.", role: "Traveler", quote: "Fantastic location and the indoor pool is perfect.", imageSrc: "http://img.b2bpic.net/free-photo/woman-with-backpack-map-camera_23-2147847022.jpg" },
                  { name: "David M.", role: "Business Guest", quote: "Excellent internet and great breakfast options.", imageSrc: "http://img.b2bpic.net/free-photo/portrait-mature-businessman-black-suit_23-2147955368.jpg" },
                  { name: "Elena S.", role: "Sightseer", quote: "Comfortable rooms and very helpful staff.", imageSrc: "http://img.b2bpic.net/free-photo/cheerful-young-woman-taking-selfie-ancient-gate_1262-4775.jpg" },
                  { name: "John K.", role: "Tourist", quote: "Great parking and very accessible area.", imageSrc: "http://img.b2bpic.net/free-photo/portrait-redhead-male-sunglasses-wild-city-park_613910-16378.jpg" },
                  { name: "Sara D.", role: "Family Guest", quote: "We loved the breakfast and the overall comfort.", imageSrc: "http://img.b2bpic.net/free-photo/elderly-woman_1398-165.jpg" }
                ]}
                textAnimation="fade"
              />
            </SectionErrorBoundary>
          </div>
  );
}
